services:
  - type: web
    name: mortalidad-colombia-dash
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python scripts/prepare_data.py"
    startCommand: "gunicorn app:server"

